version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: portfolio-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio_tracker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - portfolio-network

  backend:
    build: ./backend
    container_name: portfolio-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/portfolio_tracker?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - portfolio-network

  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
    networks:
      - portfolio-network

volumes:
  mysql_data:

networks:
  portfolio-network:
    driver: bridge
